spring.application.name=ecommerce

spring.datasource.url=jdbc:mysql://localhost:3306/ecomDB
spring.datasource.username=root
spring.datasource.password=sourav@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Razorpay
razorpay.key_id=rzp_test_ScpqkediqGqyBJ
razorpay.key_secret=xU63AYYjRJP6p6U68rXEvlNe

# Mail (Gmail example)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sroy7410610@gmail.com
spring.mail.password=rbce qqzt belg crlp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true